<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageVersion>
        <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0"/>
        <PackageVersion Include="Polyfill" Version="7.16.0"/>
        <PackageVersion Include="Roslynator.CodeAnalysis.Analyzers" Version="4.12.11">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageVersion>
        <GlobalPackageReference Include="Roslynator.Analyzers" Version="4.12.11"/>
        <GlobalPackageReference Include="Roslynator.Formatting.Analyzers" Version="4.12.11"/>
    </ItemGroup>
</Project>