<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="5.9.0"/>
        <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0"/>
        <PackageVersion Include="Polyfill" Version="11.2.0"/>
        <GlobalPackageReference Include="Roslynator.Analyzers" Version="5.0.0"/>
        <GlobalPackageReference Include="Roslynator.Formatting.Analyzers" Version="5.0.0"/>
    </ItemGroup>
</Project>