using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace MuseDashMirror.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public class LoggerGenerator : IIncrementalGenerator
{
    private const string LoggerAttribute = "MuseDashMirror.Attributes.LoggerAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            context.SyntaxProvider.ForAttributeWithMetadataName(LoggerAttribute,
                (node, _) => node is ClassDeclarationSyntax,
                (ctx, _) => GetLoggerData(ctx)),
            (ctx, loggerData) => ctx.AddSource(loggerData.Name + "_Logger.g.cs", $$"""
                                                                                   //------------------------------------------------------------------------------
                                                                                   // <auto-generated>
                                                                                   //     This code was generated by the MuseDashMirror source generator
                                                                                   //
                                                                                   //     Changes to this file may cause incorrect behavior and will be lost if
                                                                                   //     the code is regenerated.
                                                                                   // </auto-generated>
                                                                                   //------------------------------------------------------------------------------
                                                                                   #nullable enable

                                                                                   namespace {{loggerData.Namespace}};
                                                                                   partial class {{loggerData.Name}}
                                                                                   {
                                                                                       private static MelonLoader.MelonLogger.Instance Logger;
                                                                                   }
                                                                                   """));
    }

    private static LoggerData GetLoggerData(GeneratorAttributeSyntaxContext context) =>
        new(context.TargetSymbol.ContainingNamespace.ToString(), context.TargetSymbol.Name);
}