//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuseDashMirror.SourceGenerators.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MuseDashMirror.SourceGenerators.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoggerAttribute can only be used on partial class..
        /// </summary>
        internal static string MDM0000Description {
            get {
                return ResourceManager.GetString("MDM0000Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class {0} must have partial keyword in its declaration.
        /// </summary>
        internal static string MDM0000MessageFormat {
            get {
                return ResourceManager.GetString("MDM0000MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoggerAttribute can only be used on partial class.
        /// </summary>
        internal static string MDM0000Title {
            get {
                return ResourceManager.GetString("MDM0000Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with PnlMenuEvent attribute should have parameters of object and PnlMenuArgs types..
        /// </summary>
        internal static string MDM0100Description {
            get {
                return ResourceManager.GetString("MDM0100Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0}&apos;s parameter types must be object and PnlMenuArgs.
        /// </summary>
        internal static string MDM0100MessageFormat {
            get {
                return ResourceManager.GetString("MDM0100MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect usage of PnlMenuEvent Attribute.
        /// </summary>
        internal static string MDM0100Title {
            get {
                return ResourceManager.GetString("MDM0100Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with PnlStageEvent attribute should have parameters of object and PnlStageArgs types..
        /// </summary>
        internal static string MDM0101Description {
            get {
                return ResourceManager.GetString("MDM0101Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0}&apos;s parameter types must be object and PnlStageArgs.
        /// </summary>
        internal static string MDM0101MessageFormat {
            get {
                return ResourceManager.GetString("MDM0101MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect usage of PnlStageEvent Attribute.
        /// </summary>
        internal static string MDM0101Title {
            get {
                return ResourceManager.GetString("MDM0101Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with MenuSelectEvent attribute should have parameters of object and MenuSelectEventArgs types..
        /// </summary>
        internal static string MDM0102Description {
            get {
                return ResourceManager.GetString("MDM0102Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0}&apos;s parameter types must be object and MenuSelectEventArgs.
        /// </summary>
        internal static string MDM0102MessageFormat {
            get {
                return ResourceManager.GetString("MDM0102MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect usage of MenuSelectEvent Attribute.
        /// </summary>
        internal static string MDM0102Title {
            get {
                return ResourceManager.GetString("MDM0102Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with EnterGameScene attribute should have parameters of object and SceneEventArgs types..
        /// </summary>
        internal static string MDM0103Description {
            get {
                return ResourceManager.GetString("MDM0103Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0}&apos;s parameter types must be object and SceneEventArgs.
        /// </summary>
        internal static string MDM0103MessageFormat {
            get {
                return ResourceManager.GetString("MDM0103MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect usage of EnterGameScene Attribute.
        /// </summary>
        internal static string MDM0103Title {
            get {
                return ResourceManager.GetString("MDM0103Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with EnterLoadingScene attribute should have parameters of object and SceneEventArgs types..
        /// </summary>
        internal static string MDM0104Description {
            get {
                return ResourceManager.GetString("MDM0104Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0}&apos;s parameter types must be object and SceneEventArgs.
        /// </summary>
        internal static string MDM0104MessageFormat {
            get {
                return ResourceManager.GetString("MDM0104MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect usage of EnterLoadingScene Attribute.
        /// </summary>
        internal static string MDM0104Title {
            get {
                return ResourceManager.GetString("MDM0104Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with EnterMainScene attribute should have parameters of object and SceneEventArgs types..
        /// </summary>
        internal static string MDM0105Description {
            get {
                return ResourceManager.GetString("MDM0105Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0}&apos;s parameter types must be object and SceneEventArgs.
        /// </summary>
        internal static string MDM0105MessageFormat {
            get {
                return ResourceManager.GetString("MDM0105MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect usage of EnterMainScene Attribute.
        /// </summary>
        internal static string MDM0105Title {
            get {
                return ResourceManager.GetString("MDM0105Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with ExitGameScene attribute should have parameters of object and SceneEventArgs types..
        /// </summary>
        internal static string MDM0106Description {
            get {
                return ResourceManager.GetString("MDM0106Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0}&apos;s parameter types must be object and SceneEventArgs.
        /// </summary>
        internal static string MDM0106MessageFormat {
            get {
                return ResourceManager.GetString("MDM0106MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect usage of ExitGameScene Attribute.
        /// </summary>
        internal static string MDM0106Title {
            get {
                return ResourceManager.GetString("MDM0106Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with ExitLoadingScene attribute should have parameters of object and SceneEventArgs types..
        /// </summary>
        internal static string MDM0107Description {
            get {
                return ResourceManager.GetString("MDM0107Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0}&apos;s parameter types must be object and SceneEventArgs.
        /// </summary>
        internal static string MDM0107MessageFormat {
            get {
                return ResourceManager.GetString("MDM0107MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect usage of ExitLoadingScene Attribute.
        /// </summary>
        internal static string MDM0107Title {
            get {
                return ResourceManager.GetString("MDM0107Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with ExitMainScene attribute should have parameters of object and SceneEventArgs types..
        /// </summary>
        internal static string MDM0108Description {
            get {
                return ResourceManager.GetString("MDM0108Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0}&apos;s parameter types must be object and SceneEventArgs.
        /// </summary>
        internal static string MDM0108MessageFormat {
            get {
                return ResourceManager.GetString("MDM0108MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect usage of ExitMainScene Attribute.
        /// </summary>
        internal static string MDM0108Title {
            get {
                return ResourceManager.GetString("MDM0108Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with EnterWelcomeScene attribute should have parameters of object and SceneEventArgs types..
        /// </summary>
        internal static string MDM0109Description {
            get {
                return ResourceManager.GetString("MDM0109Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0}&apos;s parameter types must be object and SceneEventArgs.
        /// </summary>
        internal static string MDM0109MessageFormat {
            get {
                return ResourceManager.GetString("MDM0109MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect usage of EnterWelcomeScene Attribute.
        /// </summary>
        internal static string MDM0109Title {
            get {
                return ResourceManager.GetString("MDM0109Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with ExitWelcomeScene attribute should have parameters of object and SceneEventArgs types..
        /// </summary>
        internal static string MDM0110Description {
            get {
                return ResourceManager.GetString("MDM0110Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0}&apos;s parameter types must be object and SceneEventArgs.
        /// </summary>
        internal static string MDM0110MessageFormat {
            get {
                return ResourceManager.GetString("MDM0110MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect usage of ExitWelcomeScene Attribute.
        /// </summary>
        internal static string MDM0110Title {
            get {
                return ResourceManager.GetString("MDM0110Title", resourceCulture);
            }
        }
    }
}
