//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuseDashMirror.SourceGenerators.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MuseDashMirror.SourceGenerators.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger attribute can only be used on partial class..
        /// </summary>
        internal static string MDM0000Description {
            get {
                return ResourceManager.GetString("MDM0000Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class {0} must have partial keyword in its declaration for generating Logger.
        /// </summary>
        internal static string MDM0000MessageFormat {
            get {
                return ResourceManager.GetString("MDM0000MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger attribute can only be used on partial class.
        /// </summary>
        internal static string MDM0000Title {
            get {
                return ResourceManager.GetString("MDM0000Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class inherited from MelonMod class should be partial to register methods..
        /// </summary>
        internal static string MDM0001Description {
            get {
                return ResourceManager.GetString("MDM0001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To ensure the correct registry of MuseDashMirror attributes, {0} class should be partial.
        /// </summary>
        internal static string MDM0001MessageFormat {
            get {
                return ResourceManager.GetString("MDM0001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class inherited from MelonMod class should be partial.
        /// </summary>
        internal static string MDM0001Title {
            get {
                return ResourceManager.GetString("MDM0001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with PatchEvent attribute must have parameter types object and EventArgs..
        /// </summary>
        internal static string MDM0100Description {
            get {
                return ResourceManager.GetString("MDM0100Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} with attribute {1} must have parameter types object and {2}.
        /// </summary>
        internal static string MDM0100MessageFormat {
            get {
                return ResourceManager.GetString("MDM0100MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect parameter types.
        /// </summary>
        internal static string MDM0100Title {
            get {
                return ResourceManager.GetString("MDM0100Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with SceneEvent attribute must have parameter types object and SceneEventArgs..
        /// </summary>
        internal static string MDM0101Description {
            get {
                return ResourceManager.GetString("MDM0101Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} with attribute {1} must have parameter types object and SceneEventArgs.
        /// </summary>
        internal static string MDM0101MessageFormat {
            get {
                return ResourceManager.GetString("MDM0101MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect parameter types.
        /// </summary>
        internal static string MDM0101Title {
            get {
                return ResourceManager.GetString("MDM0101Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with Event attribute must have return type void..
        /// </summary>
        internal static string MDM0102Description {
            get {
                return ResourceManager.GetString("MDM0102Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} with attribute {1} must have return type void.
        /// </summary>
        internal static string MDM0102MessageFormat {
            get {
                return ResourceManager.GetString("MDM0102MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect return type.
        /// </summary>
        internal static string MDM0102Title {
            get {
                return ResourceManager.GetString("MDM0102Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with static class or register type static constructor must be declared as static..
        /// </summary>
        internal static string MDM0103Description {
            get {
                return ResourceManager.GetString("MDM0103Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} must be declared as static in order to be correctly registered.
        /// </summary>
        internal static string MDM0103MessageFormat {
            get {
                return ResourceManager.GetString("MDM0103MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method should be static.
        /// </summary>
        internal static string MDM0103Title {
            get {
                return ResourceManager.GetString("MDM0103Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with Event attribute must be in a partial class..
        /// </summary>
        internal static string MDM0104Description {
            get {
                return ResourceManager.GetString("MDM0104Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class {0} must be a partial class for {1}&apos;s register method to be correctly generated.
        /// </summary>
        internal static string MDM0104MessageFormat {
            get {
                return ResourceManager.GetString("MDM0104MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method should be in a partial class.
        /// </summary>
        internal static string MDM0104Title {
            get {
                return ResourceManager.GetString("MDM0104Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property/Field with PnlMenuToggle attribute must be declared in a partial class..
        /// </summary>
        internal static string MDM0200Description {
            get {
                return ResourceManager.GetString("MDM0200Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class {0} must be a partial class for {1}&apos;s register method to be correctly generated.
        /// </summary>
        internal static string MDM0200MessageFormat {
            get {
                return ResourceManager.GetString("MDM0200MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property/Field should be in a partial class.
        /// </summary>
        internal static string MDM0200Title {
            get {
                return ResourceManager.GetString("MDM0200Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property/Field with attribute PnlMenuToggle should be type UnityEngine.GameObject.
        /// </summary>
        internal static string MDM0201Description {
            get {
                return ResourceManager.GetString("MDM0201Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property/Field {0} should be type UnityEngine.GameObject.
        /// </summary>
        internal static string MDM0201MessageFormat {
            get {
                return ResourceManager.GetString("MDM0201MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect declare type.
        /// </summary>
        internal static string MDM0201Title {
            get {
                return ResourceManager.GetString("MDM0201Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property/Field should be static to be registered by MuseDashMirror.
        /// </summary>
        internal static string MDM0202Description {
            get {
                return ResourceManager.GetString("MDM0202Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property/Field {0} should be static for correct register.
        /// </summary>
        internal static string MDM0202MessageFormat {
            get {
                return ResourceManager.GetString("MDM0202MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property/Field should be static.
        /// </summary>
        internal static string MDM0202Title {
            get {
                return ResourceManager.GetString("MDM0202Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PnlMenuToggle attribute can only apply to one field..
        /// </summary>
        internal static string MDM0203Description {
            get {
                return ResourceManager.GetString("MDM0203Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PnlMenuToggle attribute can only apply to one field, leave {0} only for correct code generation.
        /// </summary>
        internal static string MDM0203MessageFormat {
            get {
                return ResourceManager.GetString("MDM0203MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect field declaration.
        /// </summary>
        internal static string MDM0203Title {
            get {
                return ResourceManager.GetString("MDM0203Title", resourceCulture);
            }
        }
    }
}
