//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuseDashMirror.SourceGenerators.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MuseDashMirror.SourceGenerators.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger attribute can only be used on partial class..
        /// </summary>
        internal static string MDM0000Description {
            get {
                return ResourceManager.GetString("MDM0000Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class {0} must have partial keyword in its declaration.
        /// </summary>
        internal static string MDM0000MessageFormat {
            get {
                return ResourceManager.GetString("MDM0000MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger attribute can only be used on partial class.
        /// </summary>
        internal static string MDM0000Title {
            get {
                return ResourceManager.GetString("MDM0000Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with PnlMenuEvent attribute should have parameters of object and PnlMenuArgs types..
        /// </summary>
        internal static string MDM0100Description {
            get {
                return ResourceManager.GetString("MDM0100Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0}&apos;s parameter types must be object and PnlMenuArgs.
        /// </summary>
        internal static string MDM0100MessageFormat {
            get {
                return ResourceManager.GetString("MDM0100MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect usage of PnlMenuEvent Attribute.
        /// </summary>
        internal static string MDM0100Title {
            get {
                return ResourceManager.GetString("MDM0100Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with PnlStageEvent attribute should have parameters of object and PnlStageArgs types..
        /// </summary>
        internal static string MDM0101Description {
            get {
                return ResourceManager.GetString("MDM0101Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0}&apos;s parameter types must be object and PnlStageArgs.
        /// </summary>
        internal static string MDM0101MessageFormat {
            get {
                return ResourceManager.GetString("MDM0101MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect usage of PnlStageEvent Attribute.
        /// </summary>
        internal static string MDM0101Title {
            get {
                return ResourceManager.GetString("MDM0101Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with MenuSelectEvent attribute should have parameters of object and MenuSelectEventArgs types..
        /// </summary>
        internal static string MDM0102Description {
            get {
                return ResourceManager.GetString("MDM0102Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0}&apos;s parameter types must be object and MenuSelectEventArgs.
        /// </summary>
        internal static string MDM0102MessageFormat {
            get {
                return ResourceManager.GetString("MDM0102MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect usage of MenuSelectEvent Attribute.
        /// </summary>
        internal static string MDM0102Title {
            get {
                return ResourceManager.GetString("MDM0102Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with SceneEvent attribute must have parameter types of object and SceneEventArgs..
        /// </summary>
        internal static string MDM0103Description {
            get {
                return ResourceManager.GetString("MDM0103Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} with {1} attribute must have parameter types object and SceneEventArgs.
        /// </summary>
        internal static string MDM0103MessageFormat {
            get {
                return ResourceManager.GetString("MDM0103MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect usage of SceneEvent attribute.
        /// </summary>
        internal static string MDM0103Title {
            get {
                return ResourceManager.GetString("MDM0103Title", resourceCulture);
            }
        }
    }
}
