namespace MuseDashMirror.Attributes;

/// <summary>
///     <para>Register the methods generated by source generator in <b>Muse Dash Mirror</b></para>
///     <example>
///         <code>
///         [RegisterInMuseDashMirror]
///         internal partial class ExampleClass;
///         </code>
///         <code>
///         [RegisterInMuseDashMirror(RegisterMethodType.Method)]
///         internal static partial class ExampleClass;
///         </code>
///     </example>
/// </summary>
/// <param name="registerMethodType">Register Method Type</param>
[AttributeUsage(AttributeTargets.Class)]
public sealed class RegisterInMuseDashMirrorAttribute(RegisterMethodType registerMethodType = RegisterMethodType.StaticConstructor) : Attribute;