//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuseDashMirror.CodeAnalysis.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MuseDashMirror.CodeAnalysis.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with PatchEvent attribute must have parameter types object and EventArgs..
        /// </summary>
        internal static string MDM0000Description {
            get {
                return ResourceManager.GetString("MDM0000Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} with attribute {1} must have parameter types object and {2}.
        /// </summary>
        internal static string MDM0000MessageFormat {
            get {
                return ResourceManager.GetString("MDM0000MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect parameter types.
        /// </summary>
        internal static string MDM0000Title {
            get {
                return ResourceManager.GetString("MDM0000Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with SceneEvent attribute must have parameter types object and SceneEventArgs..
        /// </summary>
        internal static string MDM0001Description {
            get {
                return ResourceManager.GetString("MDM0001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} with attribute {1} must have parameter types object and SceneEventArgs.
        /// </summary>
        internal static string MDM0001MessageFormat {
            get {
                return ResourceManager.GetString("MDM0001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect parameter types.
        /// </summary>
        internal static string MDM0001Title {
            get {
                return ResourceManager.GetString("MDM0001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with Event attribute must have return type void..
        /// </summary>
        internal static string MDM0002Description {
            get {
                return ResourceManager.GetString("MDM0002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} with attribute {1} must have return type void.
        /// </summary>
        internal static string MDM0002MessageFormat {
            get {
                return ResourceManager.GetString("MDM0002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect return type.
        /// </summary>
        internal static string MDM0002Title {
            get {
                return ResourceManager.GetString("MDM0002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with static class or register type static constructor must be declared as static..
        /// </summary>
        internal static string MDM0003Description {
            get {
                return ResourceManager.GetString("MDM0003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} must be declared as static in order to be correctly registered.
        /// </summary>
        internal static string MDM0003MessageFormat {
            get {
                return ResourceManager.GetString("MDM0003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method should be static.
        /// </summary>
        internal static string MDM0003Title {
            get {
                return ResourceManager.GetString("MDM0003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property/Field with attribute PnlMenuToggle should be type UnityEngine.GameObject.
        /// </summary>
        internal static string MDM0004Description {
            get {
                return ResourceManager.GetString("MDM0004Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property/Field {0} should be type UnityEngine.GameObject.
        /// </summary>
        internal static string MDM0004MessageFormat {
            get {
                return ResourceManager.GetString("MDM0004MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect declare type.
        /// </summary>
        internal static string MDM0004Title {
            get {
                return ResourceManager.GetString("MDM0004Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property/Field should be static to be registered by MuseDashMirror.
        /// </summary>
        internal static string MDM0005Description {
            get {
                return ResourceManager.GetString("MDM0005Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property/Field {0} should be static for correct register.
        /// </summary>
        internal static string MDM0005MessageFormat {
            get {
                return ResourceManager.GetString("MDM0005MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property/Field should be static.
        /// </summary>
        internal static string MDM0005Title {
            get {
                return ResourceManager.GetString("MDM0005Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PnlMenuToggle attribute can only apply to one field..
        /// </summary>
        internal static string MDM0006Description {
            get {
                return ResourceManager.GetString("MDM0006Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PnlMenuToggle attribute can only apply to one field, leave {0} only for correct code generation.
        /// </summary>
        internal static string MDM0006MessageFormat {
            get {
                return ResourceManager.GetString("MDM0006MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect field declaration.
        /// </summary>
        internal static string MDM0006Title {
            get {
                return ResourceManager.GetString("MDM0006Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Boolean and ToggleGroup member arguments of PnlMenuToggle must use nameof to reference a field or property..
        /// </summary>
        internal static string MDM0007Description {
            get {
                return ResourceManager.GetString("MDM0007Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Argument {0} of PnlMenuToggle must use nameof to reference a field or property.
        /// </summary>
        internal static string MDM0007MessageFormat {
            get {
                return ResourceManager.GetString("MDM0007MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Member argument must use nameof.
        /// </summary>
        internal static string MDM0007Title {
            get {
                return ResourceManager.GetString("MDM0007Title", resourceCulture);
            }
        }
    }
}
