global using System.Collections.Immutable;
global using System.Text.RegularExpressions;
global using Cysharp.Text;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CSharp;
global using Microsoft.CodeAnalysis.CSharp.Syntax;
global using Microsoft.CodeAnalysis.Diagnostics;
global using Microsoft.CodeAnalysis.Text;
global using MuseDashMirror.Shared;
global using MuseDashMirror.SourceGenerators.Localization;
global using static MuseDashMirror.SourceGenerators.AttributeNameHelper;
global using static MuseDashMirror.SourceGenerators.BuildInfo;
global using static MuseDashMirror.SourceGenerators.DiagnosticDescriptors;
global using static MuseDashMirror.SourceGenerators.Localization.Resources;
global using static MuseDashMirror.SourceGenerators.SourceGenerationTexts;
global using static MuseDashMirror.SourceGenerators.Utils;