global using System.Collections.Immutable;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CSharp;
global using Microsoft.CodeAnalysis.CSharp.Syntax;
global using Microsoft.CodeAnalysis.Diagnostics;
global using MuseDashMirror.Core;
global using MuseDashMirror.SourceGenerators.Localization;
global using static MuseDashMirror.SourceGenerators.AttributeFullNames;
global using static MuseDashMirror.SourceGenerators.BuildInfo;
global using static MuseDashMirror.SourceGenerators.Localization.Resources;
global using static MuseDashMirror.SourceGenerators.SourceGenerationTexts;
global using static MuseDashMirror.SourceGenerators.Utils;