namespace MuseDashMirror.SourceGenerators;

public static class SourceGenerationTexts
{
    public const string Header = """
                                 //------------------------------------------------------------------------------
                                 // <auto-generated>
                                 //     This code was generated by the MuseDashMirror source generator
                                 //
                                 //     Changes to this file may cause incorrect behavior and will be lost if
                                 //     the code is regenerated.
                                 // </auto-generated>
                                 //------------------------------------------------------------------------------
                                 #nullable enable
                                 """;

    public const string Attribute = Header + """
                                             namespace MuseDashMirror.Attributes;

                                             [global::System.AttributeUsage(global::System.AttributeTargets.Property)]
                                             public class PnlAAAAAttribute : global::System.Attribute
                                             {

                                             }
                                             """;
}