namespace MuseDashMirror.SourceGenerators;

internal static class SourceGenerationTexts
{
    internal const string Header = """
                                   //------------------------------------------------------------------------------
                                   // <auto-generated>
                                   //     This code was generated by the MuseDashMirror source generator
                                   //
                                   //     Changes to this file may cause incorrect behavior and will be lost if
                                   //     the code is regenerated.
                                   // </auto-generated>
                                   //------------------------------------------------------------------------------

                                   #nullable enable


                                   """;

    internal const string Attribute = Header + """
                                               namespace MuseDashMirror.Attributes;

                                               [global::System.AttributeUsage(global::System.AttributeTargets.Property)]
                                               public class PnlAAAAAttribute : global::System.Attribute
                                               {

                                               }
                                               """;

    internal static string GetFullName(string generatorName) => $"{SourceGeneratorNamespace}.{generatorName}";
}